= logback 用法讲解
shishaodong <spring-boot@qq.com>
v1.0,2021-03-16
:pdf-themesdir: ../themes
:pdf-fontsdir: ../fonts
:pdf-theme: KaiGenGothicCN

:toc:
:imagesdir: image
:author: Shishaodong
:mail: spring-boot@qq.com
:icons: font


常用节点结构图

[TIP]
.LogBack 基本用法
====
logback 实战
====

logback 配置文件主要组成部分

[ditaa]
----
                          +----------+
                     +--->| appender |
                     |    +----------+
                     |
+---------------+    |    +----------+
| configuration |----+--->| logger   |
+---------------+    |    +----------+
                     |
                     |    +----------+
                     +--->| root     |
                          +----------+
----

== configuration 属性

[source,xml]
----
<configuration scan="true" scanPeriod="60 seconds" debug="false">
　　  <!--其他配置省略-->
</configuration>
----

|===
^|配置项 ^|默认值 ^|描述

^|scan
^|true
|配置文件发生改变将会重新加载

^|scanPeriod
^|1分钟
|设置监测配置文件是否有修改的时间间隔，如果没有给出时间单位，默认单位是毫秒。当scan为true时，此属性生效.

^|debug
^|false
|当此属性设置为true时，将打印出logback内部日志信息，实时查看logback运行状态
|===

可以在 configuration 中定义一些全局常量 如,日志打印路径

[source,xml]
----
<property name="LOG_HOME" value="spring-boot-logback/log"/>
----

== appender

负责写日志的组件,他有两个必要的属性
`name` 和 `class`.name 用来指定 appender 名称, class 指定 appender 的全限定名.
如,`<appender name="STD_OUT" class="ch.qos.logback.core.ConsoleAppender">`

常见的 `appender` 有

`ConsoleAppender`

全限定名 `ch.qos.logback.core.ConsoleAppender`


`RollingFileAppender`

全限定名 `ch.qos.logback.core.rolling.RollingFileAppender`

`SizeAndTimeBasedRollingPolicy`
全限定名 `ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy`

|===
^|名称 ^|是否常用 ^|描述

|ch.qos.logback.core.ConsoleAppender
|否
|把日志输出到控制台

|ch.qos.logback.core.rolling.RollingFileAppender
|是
|日志输出到文件

|ch.qos.logback.core.FileAppender
|否
|日志输出到文件
|===

Appender::
. ConsoleAppender ConsoleAppender 把日志输出到控制台，有以下子节点: +
<encoder>：对日志进行格式化。 +
<target>：字符串System.out(默认)或者System.err

示例：把>=DEBUG级别的日志都输出到控制台

[source,xml]
----
<configuration>
　　　<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
　　　　　 <encoder>
　　　　　　　　　<pattern>%-4relative [%thread] %-5level %logger{35} - %msg %n</pattern>
　　　　　 </encoder>
　　　</appender>

　　　<root level="DEBUG">
　　　　　　<appender-ref ref="STDOUT" />
　　　</root>
</configuration>
----

. FileAppender 把日志添加到文件，有以下子节点: +
<file>：被写入的文件名，可以是相对目录，也可以是绝对目录，如果上级目录不存在会自动创建，没有默认值。 +
<append>：如果是 true，日志被追加到文件结尾，如果是 false，清空现存文件，默认是true。 +
<encoder>：对记录事件进行格式化。（具体参数稍后讲解 ） +
<prudent>：如果是 true，日志会被安全的写入文件，即使其他的FileAppender也在向此文件做写入操作，效率低，默认是 false。 +
示例：把>=DEBUG级别的日志都输出到testFile.log

[source,xml]
----
<configuration>
    <appender name="FILE" class="ch.qos.logback.core.FileAppender">
　　　　　<file>testFile.log</file>
　　　　　<append>true</append>
　　　　　<encoder>
　　　　　   <pattern>%-4relative [%thread] %-5level %logger{35} - %msg%n</pattern>
        </encoder>
    </appender>
    <root level="DEBUG">　　　　
        <appender-ref ref="FILE" />
    </root>
</configuration>
----

. RollingFileAppender 滚动记录文件，先将日志记录到指定文件，当符合某个条件时，将日志记录到其他文件。有以下子节点: +
<file>：被写入的文件名，可以是相对目录，也可以是绝对目录，如果上级目录不存在会自动创建，没有默认值。 +
<append>：如果是 true，日志被追加到文件结尾，如果是 false，清空现存文件，默认是true。 +
<rollingPolicy>:当发生滚动时，决定RollingFileAppender的行为，涉及文件移动和重命名。属性class定义具体的滚动策略类.

ch.qos.logback.core.rolling.TimeBasedRollingPolicy

ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy

ch.qos.logback.core.rolling.FixedWindowRollingPolicy

[source,xml]
----
<configuration>
    <!-- INFO 日志写入到文件中,外部访问的同步日志,只接受 INFO 级别的日志 -->
    <appender name="DEBUG_ACCESS" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <!-- filter 必须写在前面才能生效 -->
        <filter class="ch.qos.logback.classic.filter.LevelFilter">
            <!-- 设置日志级别 -->
            <level>DEBUG</level>
            <!-- 如果跟该日志水平相匹配，则接受 -->
            <onMatch>ACCEPT</onMatch>
            <!-- 如果跟该日志水平不匹配，则过滤掉 -->
            <onMismatch>DENY</onMismatch>
        </filter>
        <!-- 文件路径 -->
        <file>log/info.log</file>
        <!-- 滚动策略 -->
        <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
            <!-- rollover daily -->
            <fileNamePattern>${LOG_HOME}/info/risk-access-%d{yyyy-MM-dd}.%i.log</fileNamePattern>
            <!-- each file should be at most 100MB, keep 60 days worth of history, but at most 20GB -->
            <maxFileSize>10MB</maxFileSize>
            <!-- 15 天的时间周期，日志量最大 100MB-->
            <maxHistory>15</maxHistory>
            <totalSizeCap>100MB</totalSizeCap>
        </rollingPolicy>
        <!-- 格式化输出 -->
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <pattern>%d{yyyy-MM-dd HH:mm:ss:SSS}|%p|%m%n</pattern>
        </encoder>
    </appender>
</configuration>
----

== logger

== root

<evaluator>: 鉴别器，常用的鉴别器是JaninoEventEvaluato，也是默认的鉴别器，

它以任意的java布尔值表达式作为求值条件，求值条件在配置文件解释过成功被动态编译，布尔值表达式返回true就表示符合过滤条件。

evaluator有个子标签<expression>，用于配置求值条件。

<onMatch>:用于配置符合过滤条件的操作

<onMismatch>:用于配置不符合过滤条件的操作

[source,xml]
----
<filter class="ch.qos.logback.core.filter.EvaluatorFilter">
  <evaluator> <!-- 默认为 ch.qos.logback.classic.boolex.JaninoEventEvaluator -->
	<expression>return message.contains("billing");</expression>
  </evaluator>
  <OnMatch>ACCEPT </OnMatch>
  <OnMismatch>DENY</OnMismatch>
</filter>
----
